---
- debug:
   var: backup_info

- debug:
    var: backupinstance

- debug:
    var: backupinstance.value

- debug:
    var: backupinstance.key

- name: "Loopa över backupinstancer"
  include_role:
    name: backup
    tasks_from: backup_source_instance_host-job
  loop: "{{ backup_dest_with_public_keys.keys() | product(backupinstance.value.jobs) | list }}"
  loop_control:
     loop_var: host_and_job
