---
# Cert files:
# Account key:                       /opt/letsencrypt/account.key
# Domain key:                        "/etc/nginx/ssl/{{ domaininstance_group.fullname }}-domain.key"
# subjectAltName for CSR:            "{{ application.path }}/letsencrypt/subjectaltname_{{ domaininstance_group.fullname }}-domain.txt"
# Certificate Signing Request (CSR): "{{ application.path }}/letsencrypt/{{ domaininstance_group.fullname }}-domain.csr"
# Letsencrypt-script:                "{{ application.path }}/letsencrypt/letsencrypt-renew-{{ domaininstance_group.fullname }}.sh"
# Signed chained cert:               "/etc/nginx/ssl/{{ domaininstance_group.fullname }}-signed_chain.crt"

# Nginx conf: /etc/nginx/conf.d/{{ organisation.name }}/{{ webinstance.fullname }}.conf

## Serveradmin ############################################################################

- include_role:
    name: serveradmin
    tasks_from: get_serveradmin
# Returns: serveradmin

# devmode for serveradmin is handle as an application to not write anything in workspace before mounted properly.
- include_role:
    name: serveradmin
    tasks_from: serveradmin_devmode
  when: applications_devmode | d(false)

### Create global folders #######################################################################

- name: "Create global folder for all applications within organisation"
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | d( 'root', true ) }}"
    group: "{{ item.group | d( 'root', true ) }}"
    setype: "{{ item.setype | default( '_default' ) }}"                  # httpd_sys_content_t
    mode: "{{ item.mode | d('u=rwx,g=rx,o=rx') }}"
  when: item.when | default(True)
  loop:
    - { path: "/etc/nginx/ssl",                                 owner: "root", group: "root", when: "{{ webserver_use_ssl }}" }
    - { path: "/etc/nginx/conf.d/{{ organisation.name }}",      owner: "root", group: "root" }
    - { path: "/home/{{ applications_devmode_user|d() }}/workspace", owner: "{{ applications_devmode_user|d() }}", group: "{{ applications_devmode_user|d() }}", when: applications_devmode | d(false) }
    - { path: "/home/{{ applications_devmode_user|d() }}/workspace/{{ organisation.name }}", owner: "{{ applications_devmode_user|d() }}", group: "{{ applications_devmode_user|d() }}", when: applications_devmode | d(false) }

#- name: "Nginx include for organisation"
#  become: yes
#  copy:
#    content: "include /etc/nginx/conf.d/{{ organisation.name }}/*.conf;"
#    dest: "/etc/nginx/conf.d/{{ organisation.name }}.conf"
#    mode: "u=rw,g=r,o=r"
#  notify: "Reload nginx"



### Loop over application instances ##################################################################
- name: "Read all applications into applications_info"
  include_tasks: get_application.yml
  loop: "{{ application_instances }}"
  loop_control:
    loop_var: application_instance
    label: "{{ application_instance.environment|default('') }}-{{ application_instance.name }}"

- name: "Nginx include for organisation"
  become: yes
  template:
    src: nginx_organisation.conf.j2
    dest: "/etc/nginx/conf.d/{{ organisation.name }}.conf"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: "Reload nginx"

- name: "Delete unused .conf-files in /etc/nginx/conf.d/{{ organisation.name }}"
  include_tasks: clean_nginx_conf.yml

# Varnar för applications variable redan finns, eftersom vi använt den när vi skapade upp.
# Detta är safe!
- name: "Include application"
  include_tasks: application.yml
  loop: "{{ applications_info }}"
  loop_control:
    loop_var: application
    label: "{{ application.environment|default('') }}-{{ application.name }}"

### Configfiler för alla applikationer/webinstancer #########################################
#- name: "Install extra packages for all applications"
#  become: yes
#  package:
#    name: >-
#      {{
#        applications_info | map(attribute='linux_packages') | flatten | unique | list
#      }}
#    state: present

- name: "Install extra packages for all applications"
  become: yes
  dnf:
    name: "{{ item.name if item is mapping else item }}"
    enablerepo: "{{ item.repo if item is mapping else omit }}"
    state: present
  loop: "{{ applications_info | map(attribute='linux_packages') | flatten | unique | list }}"

- name: "Installera alla locales"
  become: yes
  dnf:
    name: glibc-all-langpacks
    state: present

# Installera locales från alla webinstances
# https://github.com/ansible/ansible/issues/44708
- name: "Check if locales exists"
  shell: >-
    locale -a | grep -i "{{ item }}.utf8"
  register: found_locales
  changed_when: no
  failed_when: no
  loop: >-
    {{
      applications_info | map(attribute='locales') | flatten | unique | list
    }}
- name: "Create locales"
  command: >-
    localedef -i "{{ item.item }}" -f "UTF-8" "{{ item.item }}.UTF-8"
  when: item.rc != 0
  loop: "{{ found_locales.results }}"


- name: Setup cron-jobb for Letsencrypt
  become: yes
  template:
    src: letsencrypt.cron.j2
    dest: /etc/cron.d/letsencrypt
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  when: webserver_use_letsencrypt

- name: Setup lograte for webinstances (php-fpm och nginx)
  become: yes
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/applications
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: "Skapa lista med applikationer"
  become: yes
  template:
    src: list_applications.sh.j2
    dest: "{{ serveradmin.path }}/{{ organisation.command_prefix }}list_applications"
    owner: "{{ serveradmin.process_user }}"
    group: "{{ serveradmin.process_user }}"
    mode: "u=rwx,g=rx,o=rx"

- name: "Create init_devmode-script"
  become: yes
  template:
    src: init_devmode.sh.j2
    dest: "{{ serveradmin.path }}/{{ organisation.command_prefix }}init_devmode"
    owner: "{{ applications_devmode_user }}"
    group: "{{ applications_devmode_user }}"
    mode: "u=rwx,g=rw,o=r"
  when: applications_devmode | d(false)


