---
- include_role:
    name: applications
    tasks_from: default_values
    public: yes

- include_tasks: nginx.yml

- include_tasks: ssl_and_letsencrypt.yml
  when: webserver_use_ssl

- include_tasks: sendmail.yml
  when: sendmail_enable | d(false)
