---
- hosts: "{{ target }}"
  connection: "{{ connection_type | default('ssh', true) }}"
  gather_facts: yes
  collections:
    - tvartom.serveradmin
  tasks:
    # Get data from the host with sensible information, (eg password, private key)
    # This role can also read variables from files, but is not used.
    - name: "Collect facts"
      include_role:
        name: collect_facts
        tasks_from: collect_facts
      vars:
        facts_options:
          host_vars_from_host: true

    - include_role:
        name: applications