---
- hosts: "{{ target }}"
  connection: "{{ connection_type | default('ssh', true) }}"
  gather_facts: yes
  collections:
    - tvartom.serveradmin
  tasks:
    - name: "Collect facts"
      include_role:
        name: collect_facts
        tasks_from: collect_facts
      vars:
        facts_options:
          host_vars_from_host: true
    - include_role:
        name: applications
        tasks_from: default_values
        public: yes

    - include_role:
        name: basic_centos_tools
      tags:
        - bootstrap

    - include_role:
        name: mc
      tags:
        - bootstrap

    - include_role:
        name: git
      tags:
        - bootstrap

    - include_role:
        name: users
      tags:
        - bootstrap

    - include_role:
        name: mariadb
      when: mariadb_enable

    - include_role:
        name: firewall

    - include_role:
        name: java_and_maven
      when: java_and_maven_enable

    - include_role:
        name: serveradmin
      tags:
        - bootstrap

    - include_role:
        name: webserver

    - include_role:
        name: sass
      when: sass_enable

    - include_role:
        name: php
      when: php_enable

    - include_role:
        name: php_xdebug
      when: php_enable and applications_devmode and applications_devmode_xdebug

    - include_role:
        name: redis
      when: redis_enable

    - set_fact:
        applications_devmode_samba_settings:
          shares:
            - name: "workspace"
              comment: "Workspace for devmode"
              path: "/home/{{ applications_devmode_user }}/workspace"
              public: true
              browseable: true
              guest_ok: true
              writeable: true
#            write_list: "{{ applications_devmode_user }}"
              owner: "{{ applications_devmode_user }}"
              group: "{{ applications_devmode_user }}"
              setype: httpd_sys_rw_content_t
              create_mode: '0640'
              #force_create_mode: '0660'
              directory_mode: '0750'
              #force_directory_mode: '0770'
          users:
            - name: "{{ applications_devmode_user }}"
              password: ""
      when: applications_devmode and applications_devmode_samba

    - include_role:
        name: bertvv_samba
      vars:
        ansible_become: yes
        samba_workgroup: "{{ samba.workgroup|d('WORKGROUP') }}"
        samba_shares: "{{ samba.shares|d([]) + applications_devmode_samba_settings.shares|d([]) }}"
        samba_users: "{{ samba.users|d([]) + applications_devmode_samba_settings.users|d([]) }}"
        samba_netbios_name: "{{ samba.netbios_name|d(inventory_hostname) }}"
      when: applications_devmode_samba_settings is defined or samba is defined

    - include_role:
        name: nfs
      when: applications_devmode and applications_devmode_nfs
      vars:
        nfs:
          exports:
            - comment: "Workspace for devmode"
              path: "/home/{{ applications_devmode_user }}/workspace"
              rw: true
              owner: "{{ applications_devmode_user }}"
              async: true
              fsid: root

    - include_role:
        name: autofs
      when: autofs is defined

