---
- hosts: "{{ target }}"
  connection: "{{ connection_type | default('ssh', true) }}"
  gather_facts: yes
  collections:
    - tvartom.serveradmin
  tasks:
    # Get data from the host with sensible information, (eg password, private key)
    # This role can also read variables from files, but is not used.
    - name: "Collect facts"
      include_role:
        name: collect_facts
        tasks_from: collect_facts
      vars:
        facts_options:
          host_vars_from_host: true
          diskspace_message: true

    - name: Visa info
      debug:
        var: active_webinstances

    - name: Visa info
      debug:
        var: ansible_facts

    - name: Hostname
      debug:
        msg: "inventory_hostname: {{ inventory_hostname }}, inventory_hostname_short: {{ inventory_hostname_short }}"

    - name: from remote host_vars
      debug:
        var: mariadb

    - name: colorcodes
      debug:
        var: yamlcolors

    - name: colors
      debug:
        var: bashcolors

    - name: Använt diskutrymme
      debug:
        var: diskspace_message
